# 图形验证码配置
parameters:
    captcha:
        width:          150   # 图片宽度（像素）
        height:         50    # 图片高度（像素）
        length:         4     # 验证码字符个数
        ignore:         false # 纯文字极速模式
        charset:        'abcdefhjkmnprstuvwxyz23456789'  # 字符集（已排除易混淆字符）
        distortion:     false # 关闭扭曲提升性能
        interpolation:  false # 关闭插值提升性能
